### ISSUE TITLE
v0.7.2 is not working on Firefox ESR 45

### ISSUE THREAD

**Issue by phts** [NiklasGollenstede/unload-tabs#10]
Tried to use versions from 0.7.2-b1 to 0.7.2 - still not working (no "Unload" items in the context menu).
There is an error in browser console:

```js
SyntaxError {
  fileName: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://unload-tabs/main.js",
  lineNumber: 107,
  message: "missing : after property id",
  stack: "@resource://unload-tabs/main.js:107:undefinedrun@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1"
}
```

Although 0.7.1 seems to be working fine in FF ESR 45.

**Comment by NiklasGollenstede** [comment]
I can confirm that this error occurs in ESR 45, but I don't really know whats causing it. Finding such edge-case syntax errors can be incredibly annoying. (For starters, there is no property id anywhere near line 107 ...).

Since ESR 45 will reach it's end of support in a month and v0.7.1 works, I don't really want to put any energy in this. I've adjusted the compatibility of the newer versions.
