### ISSUE TITLE
[Feature Request] Unload tabs from all windows

### ISSUE THREAD

**Issue by stevenengler** [NiklasGollenstede/unload-tabs#23]
Hi, just wanted to mention it would be nice to have a third menu option that unloads tabs in all windows rather than only the current window. This would be useful when there are 10+ windows open on multiple desktops, and the Firefox memory usage is high.

**Comment by NiklasGollenstede** [comment]
I think I thought about this but rejected the idea because unloading all tabs is almost the same as just restarting the browser, which I am pretty sure is more efficient as far as freeing resources is concerned.

The major difference between unloading all inactive tabs and restarting the browser (e.g. with the button on `about:profiles`) is that the active tabs would be reloaded (from the session cache, though), extensions are reloaded and the windows would be re-opened (which may be annoying with multiple desktops).

Ok, writing down my arguments not to do this I just convinced myself that it is probably a good Idea to add this option ... so I will do it.

**Comment by NiklasGollenstede** [comment]
I have added it. Here is the current beta version: https://github.com/NiklasGollenstede/unload-tabs/releases/tag/v0.8.3b21

I've only done a single test with two windows.
Could you please [install it](https://github.com/NiklasGollenstede/unload-tabs#development-builds----) and test it a bit more toughly over the next couple of days?
Afterwards I'll upload it to AMO.

**Comment by stevenengler** [comment]
@NiklasGollenstede Thanks for adding this so quickly! This definitely helps when using multiple desktops / workspaces. I've installed it and it's working great so far with ~10 windows. It took me a few minutes of looking at the diff to see that the option is only available through the tools menu (which is hidden by default on Firefox nowadays), but now that I know where it is it's working great. I'll post back here if I find any problems.

**Comment by stevenengler** [comment]
Two weeks later, still seems to be working fine for me.

**Comment by NiklasGollenstede** [comment]
Thanks for the feedback (and reminder). It's now released on AMO as v0.8.3!
