### ISSUE TITLE
Unload tree

### ISSUE THREAD

**Issue by laptop006** [NiklasGollenstede/unload-tabs#25]
Prior to FF Quantum I used the "suspend tree" option of the Suspend Tabs + Tree Style Tabs combo, is there any way similar action could be added?

Simply unloading all tabs in the selected container would be close enough for my uses.

**Comment by NiklasGollenstede** [comment]
I have added an "Unload Tree" menu option, but it only appears in the sidebar.
Here is the current beta version: https://github.com/NiklasGollenstede/unload-tabs/releases/tag/v0.8.4b22

I've only done a simple test with a few children.
Could you please [install it](https://github.com/NiklasGollenstede/unload-tabs#development-builds----) and test it a bit more toughly over the next couple of days?
Afterwards I'll upload it to AMO.

**Comment by BobbyWibowo** [comment]
I tried the latest dev build (0.8.4b23), but I don't see any "Unload Tree" option in TST sidebar. Only the usual "Unload Tab" and "Unload Other Tabs".
I tried clicking on the [RESET] thing, but that did nothing noticeable.

**Comment by NiklasGollenstede** [comment]
Yes, this worked for a (short?) while and then broke due to new features in Firefox/TST. (The additional menu was only added to the now hidden emulated menu, not to the newly available native context menu on the sidebar.)
The @piroor, the author of TST, actually recently made me aware (#31) of these changes, but I just now made the time to understand and address the issue.

Now the problem should be fixed for good (in 0.8.4b26). I'll release this version on AMO as 0.8.4 as well.
