### ISSUE TITLE
[Feature Request] Confirm before reloading an unloaded tab

### ISSUE THREAD

**Issue by Israfael** [NiklasGollenstede/unload-tabs#27]
Hi,
love the extension - the only thing that I miss is a confirmation before actually re-loading a tab (e.g. a button on an unloaded tab).
Would it be possible to implement such a feature?

Use case:
when I have few unloaded tabs with the same title but different url's (e.g. same domain, different sub-pages) and I want to re-load one specific tab among them,
then I don't know which tab is the one by tab's title - but I will know if I see the url.
So I go through these pages one-by-one to check their url's.
Right now, each page is automatically re-loaded whenever I click on it (whether I want it to re-load or not).
Ideally, I would be able to choose whether I want to reload it or not (and look further for the one specific tab I'd like to reload).

E.g. all unloaded tabs could show a content similar to:
"
This tab is unloaded by UnloadTabs extension.
The tab's url is: https://www.example-url.com/sub-page/even-more/detail.html .
Hit the reload button below to reload this tab.
[RELOAD]
"

I know this feature is "implementable" - I don't know how "feasible" it is to implement. :)
While I'm reluctant to point to another extension, there's only one that I found (for FF-Quantum) that has this feature: "Freeze, Tab Suspender". (But it doesn't provide any automated tab-unloading, so doesn't provide any value to how I use FF.)

**Comment by NiklasGollenstede** [comment]
That extension (poorly) does what a lot of (older) "Tab Suspender" extensions (exp. for chrome) do: it doesn't actually unload the page in the tab, it replaces it with an extension page that has the option to load the original page again.

The fundamental problem with that approach is that browsers simply close those tabs when the extension gets removed, in Firefox even when it gets updated.
I.e. you suspend tabs, Firefox decides its time to update your extensions, your tabs are gone. That is completely unacceptable.
There are ways around this, but they are all hacks to some extend.

Your actual problem is that the UI doesn't allow you to see the URL of a tab without selecting it. I am sure there are solutions for that.

So thanks for using UnloadTbs, but I won't change this behavior.
The next thing I will do for this extension is to use Firefox's new Tab Successor API to better prevent automatically loading unloaded tabs after closing tabs. But even that I won't be able to start before April or so.
