### ISSUE TITLE
Dim unloaded tabs CSS no longer works with firefox 69

### ISSUE THREAD

**Issue by flying-sheep** [NiklasGollenstede/unload-tabs#32]
I had to replace

```css
@-moz-document url(chrome://browser/content/browser.xul) {
```

with

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
```

**Comment by NiklasGollenstede** [comment]
Ah, yes. I ran into this before, but forgot to update it here as well. Thanks for pointing it out!

The problem is that the main UI file was renamed, from `browser.xul` to `browser.xhtml`.
Your fix also kind-of works because it completely removes the file name restriction (but it makes the style slightly less efficient, because the browser now also tries to apply it to other UI elements).
Also, the namespace might very well change to HTML in the foreseeable future, so I think it is safer not to include one.

**Comment by NiklasGollenstede** [comment]
Ok, new version with updated CSS code and instructions is submitted to addons.mozilla.org!

**Comment by flying-sheep** [comment]
Great, thank you!
