### ISSUE TITLE
Bug: Unload other tabs doesn't unload pinned tabs

### ISSUE THREAD

**Issue by Ambiwlans** [NiklasGollenstede/unload-tabs#45]
Probably not a hard fix. Manually right clicking a pin and unloading it works. I guess they are kept in a separate list

**Comment by NiklasGollenstede** [comment]
That is actually [by design](https://github.com/NiklasGollenstede/unload-tabs/blob/master/background/index.js#L111). By default, Firefox also treats pinned tabs differently: (when restoring a session) they are loaded directly upon startup, while al other tabs are loaded on demand (i.e. remain "unloaded").

If you invoke "Unload Other Tabs" on a pinned tab though, it will unload all tabs, including pinned ones (excluding the currently active tab and the one targeted by the context menu).
